### ISSUE TITLE
New Term for W08: Calibrator

### ISSUE THREAD

**Issue by adamml** [nvs-vocabs/SWEMarineProfileVocabs#2]
I'd like to request the above addition please:

Contact details for a person or organisation that is responsible for conducting the calibration of a device or system.

**Comment by adamml** [comment]
Bump

**Comment by ptagliolato** [comment]
Maybe it should be a sub-term of http://vocab.nerc.ac.uk/collection/W08/current/CONT0003/

**Comment by adamml** [comment]
@ptagliolato If you are happy that a calibration fits the definition of operation here, then yes calibrator could be a six-term or specialisation of operator. Without further information in that term's definition, however, I would have inferred operation to mean deployment of an instrument in the environment for monitoring or measurement purposes.

**Comment by ptagliolato** [comment]
@adamml I can not get exactly your point. I think that "operate a sensor" in CONT0003 not only means to deploy it in the environment, but also: "to control the functioning of the sensor" in order to make it monitor or measure something. Maybe the english technical  meaning you are thinking about is more specific, but to sustain my claim I would refer to https://ocw.mit.edu/courses/mechanical-engineering/2-693-principles-of-oceanographic-instrument-systems-sensors-and-measurements-13-998-spring-2004/readings/lec2_irish.pdf where the term "to operate a sensor" is strictly bound to calibration, if I  understand well. What do you think?

**Comment by adamml** [comment]
Thanks @ptagliolato. I think we are in agreement. I think expanding the definition of CONT0003 to include to a reference to that document (or similar) would help.

**Comment by gwemon** [comment]
Our ref: BODCNVS-668

**Comment by louatbodc** [comment]
Hi @adamml , @ptagliolato 

I propose expanding the term CONT0003 to:

'Relevant contact information about the person or organisation that operates a device or system. Includes operators that are responsible for the deployment of sensors and operators that control the functioning of sensors such as its calibration.'

**Comment by louatbodc** [comment]
Term CONT0003 was updated to:

'Relevant contact information about the person or organisation that operates a device or system. Includes operators that are responsible for the deployment of sensors and operators that control the functioning of sensors such as its calibration.'

Please note it may take up to 24 hours for the changes to appear on our web services and endpoints.
